name: Internet Monitor
version: "0.2.0"
slug: internet_monitor
description: Monitor internet availability and record outages.

startup: services
boot: auto

init: false

host_network: true

arch:
  - aarch64
  - amd64

map:
  - addon_config:rw