name: Internet Monitor
slug: internet_monitor
description: Monitor internet connectivity and record internet outages.
version: "0.2.2"

image: ghcr.io/mariorauh/internet-monitor-backend

url: https://github.com/mariorauh/internet-monitor-backend

startup: services
boot: auto
init: false

host_network: true

arch:
  - amd64
  - aarch64

map:
  - addon_config:rw

options: {}

schema: {}